version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: 'api_php'
    volumes:
      - .:/usr/src/app
    environment:
      PHP_IDE_CONFIG: "serverName=api_docker"
    networks:
      - api_app

  nginx:
    image: nginx:1.21.1
    container_name: 'api_nginx'
    ports:
      - '81:80'
    volumes:
      - .:/usr/src/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_app

  mysql:
    image: mysql:8.0.25
    container_name: 'api_mysql'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_database
    ports:
      - 3306:3306
    networks:
      - api_app

networks:
  api_app:
